### ISSUE TITLE
[ERROR] Could not pass event PlayerJoinEvent to Cardinal v1.4.3

### ISSUE THREAD

**Issue by Khosraw** [NikV2/CardinalAPI#10]
**Discord**
Cicada3083#5634

**Error(s)**
https://pastebin.com/

**Does the issue still persist on the default config?**
**Yes**

**Is the plugin up to date?**
**Yes**

**Is ProtocolLib up to date?**
**Yes**

**Server Environment & Version**
Paper version git-Paper-33d42c8e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by NikV2** [comment]
Pastebin? o_o

**Comment by fizzrepo** [comment]
o-o
