### ISSUE TITLE
[REQUEST] Vanish AFK Message

### ISSUE THREAD

**Issue by Khosraw** [NikV2/CardinalAPI#11]
**Discord**
Cicada3083#5634

**What feature would you like to be added and why?**
Prevent an AFK message from showing up if a player in vanish goes AFK and then back. This is so if the staff is going back and forth and stays AFK for a little while, they are not revealed to be vanish.

**Comment by NikV2** [comment]
That's just essentials being essentials, i'lll try to make it so if u're standing while vanished ur character teleports up and down after a delay to avoid that
