### ISSUE TITLE
Vanish [REQUEST]

### ISSUE THREAD

**Issue by ExceptedPrism3** [NikV2/CardinalAPI#12]
**Discord**
Prism3#0003

**What feature would you like to be added and why?**
While vanished you can see the others based on a perm, like you can see them in a ghost like

**Comment by NikV2** [comment]
It used to work like that previously, But it seems to take quite long to process the vanish command and the player join event gets delayed so i've removed it, I might add it back in the future if i add a cache for players with the admins so the plugin won't have to check again.
