### ISSUE TITLE
Reports [REQUEST]

### ISSUE THREAD

**Issue by ExceptedPrism3** [NikV2/CardinalAPI#13]
**Discord**
Prism3#0003

**What feature would you like to be added and why?**
Once cardinal is installed on a Proxy Server, you go in the config and you find a discord WebHook Link that hooks with a Discord Channel to list there the new / ingoing / dealt with reports and tells what's which sub-server the report has happened and who and on who + the time xD

**Comment by NikV2** [comment]
I'll make them work with mysql in the future
