### ISSUE TITLE
[ERROR] [20:10:35 ERROR]: Could not pass event PlayerJoinEvent to Cardinal

### ISSUE THREAD

**Issue by Khosraw** [NikV2/CardinalAPI#15]
**Discord**
Cicada3083#5634

**Error(s)**
https://pastebin.com/mn20FxA4

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Paper version git-Paper-33d42c8e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by NikV2** [comment]
This error gets thrown when you reload the server or the plugin and/or the player tries to join while the plugin is loading

**Comment by NikV2** [comment]
So you definitely reloaded or the player tried to join while ur server was starting up

**Comment by Khosraw** [comment]
Possibly the second one as I didn't reload the plugin.
