### ISSUE TITLE
fly hacks[BUG]

### ISSUE THREAD

**Issue by ExceptedPrism3** [NikV2/CardinalAPI#16]
**Discord**
Prism3#4823

**Describe the bug**
have this WildernessTP plugin and once doing /wild it tp you but you get kicked for fly hacks while loading up the chunks your droping in!

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Hyperion 1.8.8

**Additional Information (Optional)**
https://pastebin.com/QryFS11p

**Comment by SleepyKolosLolya** [comment]
How did you got this bug?

**Comment by ExceptedPrism3** [comment]
> How did you got this bug?
once doing /wild it tp you but you get kicked for fly hacks while loading up the chunks your droping in!

**Comment by NikV2** [comment]
It's a mistake i made in the last update, i'll make it check for the chunk using nms
