### ISSUE TITLE
[BUG] OMG REMOVE RAT WTF THIS SUCH SCAM WTF NO RAT PLS REMOVE RAY WHY U RAT BRO

### ISSUE THREAD

**Issue by Tecnio** [NikV2/CardinalAPI#17]
**Discord**
Provide your Discord username and ID (ie: User#4252)
Make sure you're Verified on our Discord otherwise this will
Be marked as Invalid.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Does the issue still persist on the default config?**
Yes/No

**Is the plugin up to date?**
Yes/No

**Is ProtocolLib up to date?**
Yes/No

**Server Environment & Version**
Your server software (ie Paper 1.12.2)

**Additional Information (Optional)**

**Comment by NikV2** [comment]
I RAT BECAUSE I WANT TO, SAY GOODBYE TO YOUR CREDIT CARD KIDDO

**Comment by Tecnio** [comment]
OMG SO SORRY BRO I AM SO SORRY I WILL NEVER TELLL RAT TO ANYONE PLS DONT USE MY CREDIT CARD ITS MY MOMS STOP PLEASE THEY WILL BEAT ME
