### ISSUE TITLE
Speed False [FALSE POSITIVE]

### ISSUE THREAD

**Issue by ExceptedPrism3** [NikV2/CardinalAPI#3]
**Discord**
Prism3#0003

**How/When does it happen?**
Was playing normally until the server detected him as Speed

**Verbose**
https://pastebin.com/NGuNqpkV

**Video of the false positive**
-

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Spigot 1.8

**Additional Information (Optional)**
Also 10 Players playing at same time

**Comment by NikV2** [comment]
Cardinal doesn't seem to be the only plugin flagging your players for speed-fly It's also Matrix.

I need to know what the player's doing in order to cause the false flag.

Your anticheat is screaming with speed flags aswell, are u sure he's not cheating?;p

**Comment by ExceptedPrism3** [comment]
Yeah it is Screaming, I have also the Admins getting flagged.

I have a plugin that like when you hop on the server you get auto tp to the pre-set location.

There's a mili/little second before they get auto-tped so maybe because of that. I got that speed because of this like when joining the server

**Comment by NikV2** [comment]
I'll see if i can add a small threshold
