### ISSUE TITLE
Vanish [REQUEST]

### ISSUE THREAD

**Issue by ExceptedPrism3** [NikV2/CardinalAPI#4]
**Discord**
Prism3#0003

**What feature would you like to be added and why?**
Chest access animation/sound feature to be disabled while being invisible as well for pressure plate.
**Why?**
To investigate the player surroundings without any disturbances.
 
I though the chest access is there and opened a chest near a player and did the sound and the player be like "who tf? Call Ghost Busters" lol

**Comment by NikV2** [comment]
Good one^^

I'll try to add more vanish mechanics

**Comment by NikV2** [comment]
I can't seem to find a decent way to do it without a bunch of spaghetti code, Once i figure out a better way i'll make opening containers silent while vanished
