### ISSUE TITLE
Geyser Joining [FALSE POSITIVE]

### ISSUE THREAD

**Issue by ExceptedPrism3** [NikV2/CardinalAPI#6]
**Discord**
Prism3#0003

**How/When does it happen?**
By joining with Bedrock edition

**Verbose**
Provide the verbose messages
**player/address: _ExceptedPrism3 | failed: UUID Spoof | timestamp: 23.11.2020 17:55**

**Video of the false positive**
https://ibb.co/m50ypbd

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Paper 1.15.2

**Additional Information (Optional)**

**Comment by NikV2** [comment]
What in the name of fuck..
