### ISSUE TITLE
BadPacket [BUG]

### ISSUE THREAD

**Issue by ExceptedPrism3** [NikV2/CardinalAPI#7]
**Discord**
Prism3#0003

**Describe the bug**
Was doing parkour and some Movement activities

**To Reproduce**
Do some actions such as hitting, moving while jumping etc...

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Paper 1.15.2

**Additional Information (Optional)**
https://pastebin.com/mH4yGBvn
I don't know why the ping is high tho!

**Comment by NikV2** [comment]
1k Ping. god damn

**Comment by ExceptedPrism3** [comment]
I was on the Java edition and was fine

**Comment by NikV2** [comment]
Transaction ping is the delay your packets are being proccessed by Cardinal. Meaning cardinal takes around 60 average to proccess your packets which is normal.

Your normal ping seems to be very high which is quite weird. Are u sure it's not an internet issue with ur host provider? or any protocol plugins delaying ur packets?

**Comment by ExceptedPrism3** [comment]
Nope, my internet was fine + while on Bedrock I didn't feel any lag or what so ever!

**Comment by NikV2** [comment]
I can't directly **Fix** that. It detects PingSpoofing which can make Players invisible to the anticheat if the player's ping is insanely high.

Your transaction ping should always be close or remotely close to your actual ping if u're legit. But again, not sure why u're reaching 1k ping with a **Fine** Connection.

Feel free to increase the difference option in the checks.yml (BadPackets D)
