### ISSUE TITLE
[ERROR] onPacketReceiving(PacketEvent)

### ISSUE THREAD

**Issue by Khosraw** [NikV2/CardinalAPI#8]
**Discord**
Cicada3083#5634

**Error(s)**
https://pastebin.com/DsjP5Axs

**Does the issue still persist on the default config?**
**Yes**

**Is the plugin up to date?**
**Yes**

**Is ProtocolLib up to date?**
**Yes**

**Server Environment & Version**
Purpur version git-Purpur-606 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by NikV2** [comment]
Did you reload by any chance? at any state?

**Comment by Khosraw** [comment]
> Did you reload by any chance? at any state?

Nope
